"""Add Bio and profile pic

Revision ID: 09770173f24e
Revises: b4bd4dc80cdb
Create Date: 2022-05-07 09:30:41.386077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09770173f24e'
down_revision = 'b4bd4dc80cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
